### PR TITLE
Turn logs into traces

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
logInfo is enabled by default which creates unnecessary noise in quick
scripts

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
What, so trace is less verbose than info in D2? :open_mouth:

**Comment by mihails-strasuns-sociomantic** [comment]
In vibe.d logger you mean. Other way around - `info` is the default logging level if you don't configure anything and `trace` is one more verbose.

**Comment by mihails-strasuns-sociomantic** [comment]
Updated with removing explicit set of log level in example to make it more obvious

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
:+1:

**Pull request merged**
