### PR TITLE
Handle null value for repo language field

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
Came across this while playing around. @mihails-strasuns-sociomantic perhaps you've already fixed this. If so, just close.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
AFAICS there is nothing to fix, it throws `JSONException` as it should. Catch it and provide whatever default you want.

**Comment by mihails-strasuns-sociomantic** [comment]
You may want to use https://dlang.org/phobos/std_exception.html#.ifThrown to wrap such check in one line

**Comment by gavin-norman-sociomantic** [comment]
Hm I just found that it broke
```D
    auto repos = client
        .listOrganizationRepos("sociomantic")
        .filter!(repo => repo.language() == "D")
        .filter!(repo => !excluded.canFind(repo.name()))
        .map!(repo => repo.name())
        .array();
```
How would you suggest that be adapted then?

**Comment by mihails-strasuns-sociomantic** [comment]
```D
.filter!(repo => repo.language().ifThrown("") == "D")
```

**Comment by gavin-norman-sociomantic** [comment]
I see. How come you didn't have this problem in your example script to create the D2 migration project?

**Comment by mihails-strasuns-sociomantic** [comment]
I don't remember ever getting no "language" field response at that time.

**Comment by gavin-norman-sociomantic** [comment]
Hm, looks like something's changed on github's side since then.

**Pull request closed without merging**
