### PR TITLE
Update copyright owner

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I guess this project is officially abandoned anyway, right?

**Comment by mathias-baumann-sociomantic** [comment]
hmm given that @mihails-strasuns-sociomantic  moved the code into neptune.. I think so yes

**Comment by leandro-lucarella-sociomantic** [comment]
@mathias-baumann-sociomantic @mihails-strasuns @gavin-norman-sociomantic please confirm it is OK to archive this repo

**Comment by nemanja-boric-sociomantic** [comment]
I have no call/interest here.

**Comment by mihails-strasuns** [comment]
Confirmed

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/sociomantic-tsunami/octod/pull/34

**Comment by leandro-lucarella-sociomantic** [comment]
Merging so the archived repo has the update copyright.

**Pull request merged**
